fn main() {
    // errors - recoverable errors - Result<T,E> 
    // unrecoverable errors - panic! macro 



    // unrecoverable errors - panic! macro 

    panic!("explicit calling panic to interupt the program to exit ");

}
